name: Cypress con Cucumber

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev cypress cucumber

      - name: Run tests
        run: npx cypress run --features features --cucumber-opts='--format=json'

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cypress/cucumber-reports/cucumber.json
